import { jsPDF } from "jspdf";

/**
 * Generates and downloads a professional, beautifully-formatted PDF report
 * from Markdown / text generated by MediTrackr Copilot.
 * 
 * @param {string} reportText - The raw markdown / text report content.
 * @param {string} [userName] - Optional user name for the title.
 */
export const downloadReportAsPDF = (reportText, userName = "Patient") => {
  if (!reportText) return;

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "pt",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;

  let y = margin;

  // Helper to check page break
  const checkPageBreak = (neededHeight) => {
    if (y + neededHeight > pageHeight - 50) {
      doc.addPage();
      y = margin + 20;
      drawPageHeader();
    }
  };

  // Header banner on subsequent pages
  const drawPageHeader = () => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(140, 155, 165);
    doc.text("MEDITRACKR HEALTH OS • CONFIDENTIAL HEALTH REPORT", margin, margin - 10);
    doc.setDrawColor(220, 225, 230);
    doc.setLineWidth(0.5);
    doc.line(margin, margin - 5, pageWidth - margin, margin - 5);
  };

  // 1. Top Decorative Brand Banner on Page 1
  doc.setFillColor(11, 19, 38); // Dark Navy background
  doc.roundedRect(margin, y, contentWidth, 68, 6, 6, "F");

  // Brand Logo / Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(78, 222, 163); // MediTrackr Mint
  doc.text("MediTrackr", margin + 18, y + 28);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(187, 202, 191);
  doc.text("PERSONAL HEALTH OS & MEDICATION REPORT", margin + 18, y + 44);

  // Date & Patient Info on right of banner
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255);
  const dateStr = new Date().toLocaleDateString("en-US", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
  doc.text(`Generated: ${dateStr}`, pageWidth - margin - 18, y + 28, { align: "right" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(187, 202, 191);
  doc.text(`Patient: ${userName}`, pageWidth - margin - 18, y + 44, { align: "right" });

  y += 85;

  // Clean Markdown lines
  const rawLines = reportText.split("\n");

  for (let i = 0; i < rawLines.length; i++) {
    const rawLine = rawLines[i].trim();
    if (!rawLine) {
      y += 6;
      continue;
    }

    // Main Headers (# or ##)
    if (rawLine.startsWith("# ") || rawLine.startsWith("## ")) {
      checkPageBreak(35);
      const title = rawLine.replace(/^#+\s*/, "").replace(/[📋📊💡⚠️]/g, "").trim();

      y += 10;
      doc.setFillColor(240, 248, 245);
      doc.roundedRect(margin, y, contentWidth, 24, 4, 4, "F");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(16, 120, 85);
      doc.text(title, margin + 8, y + 16);

      y += 32;
    }
    // Subheaders (###)
    else if (rawLine.startsWith("### ")) {
      checkPageBreak(25);
      const subtitle = rawLine.replace(/^###\s*/, "").trim();

      y += 6;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10.5);
      doc.setTextColor(20, 35, 60);
      doc.text(subtitle, margin + 4, y);
      y += 14;
    }
    // Bullet Points (- or * or •)
    else if (rawLine.startsWith("- ") || rawLine.startsWith("* ") || rawLine.startsWith("• ")) {
      const bulletText = rawLine.replace(/^[-*•]\s*/, "");

      // Handle bold keys in bullets (e.g. "**Patient Profile**: Details")
      const cleaned = bulletText.replace(/\*\*/g, "");
      const wrapped = doc.splitTextToSize(cleaned, contentWidth - 20);

      checkPageBreak(wrapped.length * 13 + 4);

      // Draw small bullet point icon/dot
      doc.setFillColor(78, 222, 163);
      doc.circle(margin + 6, y - 3.5, 2.5, "F");

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(40, 50, 65);

      for (let j = 0; j < wrapped.length; j++) {
        doc.text(wrapped[j], margin + 16, y);
        y += 13;
      }
      y += 2;
    }
    // Numbered lists (1. , 2. )
    else if (/^\d+\.\s+/.test(rawLine)) {
      const cleaned = rawLine.replace(/\*\*/g, "");
      const wrapped = doc.splitTextToSize(cleaned, contentWidth - 16);

      checkPageBreak(wrapped.length * 13 + 4);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(20, 35, 60);

      for (let j = 0; j < wrapped.length; j++) {
        doc.text(wrapped[j], margin + 8, y);
        y += 13;
      }
      y += 2;
    }
    // Standard Paragraph / Table / Notes
    else {
      const cleaned = rawLine.replace(/\*\*/g, "").replace(/`/g, "");
      const isDisclaimer = cleaned.toLowerCase().includes("disclaimer") || cleaned.toLowerCase().includes("consult a licensed");

      if (isDisclaimer) {
        checkPageBreak(35);
        y += 8;
        doc.setFillColor(254, 243, 242);
        doc.setDrawColor(254, 205, 202);
        doc.setLineWidth(0.8);
        doc.roundedRect(margin, y, contentWidth, 32, 4, 4, "FD");

        doc.setFont("helvetica", "italic");
        doc.setFontSize(8);
        doc.setTextColor(180, 40, 35);
        const disWrapped = doc.splitTextToSize(cleaned, contentWidth - 16);
        for (let k = 0; k < disWrapped.length; k++) {
          doc.text(disWrapped[k], margin + 8, y + 12 + k * 10);
        }
        y += 40;
      } else {
        const wrapped = doc.splitTextToSize(cleaned, contentWidth);
        checkPageBreak(wrapped.length * 13);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(9.5);
        doc.setTextColor(50, 60, 75);

        for (let j = 0; j < wrapped.length; j++) {
          doc.text(wrapped[j], margin, y);
          y += 13;
        }
      }
    }
  }

  // Add Page Numbers on all pages
  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150, 160, 170);
    doc.text(
      `Page ${p} of ${totalPages} • Generated by MediTrackr`,
      pageWidth / 2,
      pageHeight - 20,
      { align: "center" }
    );
  }

  // Save the PDF
  const filename = `MediTrackr_Health_Report_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
};
